apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: z0jije1nx-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:4c35f80794c2152dda7f06b01002e34eb754192b@sha256:16e41e6e2245c31dc4dc32a0a05d5daacfbff0ad6ba5e140ad455a9acc03cedd
          name: container-image
